### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by VincentChen525** [nosiu/comfyui-instantId-faceswap#14]
how to figure it?
find model: /root/ComfyUI/models/insightface/models/antelopev2/scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/comfyui-instantId-faceswap/node.py", line 195, in create_pipeline
    pipe.load_ip_adapter_instantid(ipadapter)
  File "/root/ComfyUI/custom_nodes/comfyui-instantId-faceswap/pipeline_stable_diffusion_xl_instantid_inpaint.py", line 70, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "/root/ComfyUI/custom_nodes/comfyui-instantId-faceswap/pipeline_stable_diffusion_xl_instantid_inpaint.py", line 89, in set_image_proj_model
    state_dict = torch.load(model_ckpt, map_location="cpu")
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by nosiu** [comment]
Did you download the correct ipadapter from readme and put it into the right place?
If so then you have to also select it in the loading node

**Comment by VincentChen525** [comment]
> Did you download the correct ipadapter from readme and put it into the right place? If so then you have to also select it in the loading node

thx, the model downloaded earlier was damaged, and it can be used after re-download
