### ISSUE TITLE
Exception during processing !!!

### ISSUE THREAD

**Issue by kunieone** [nosiu/comfyui-instantId-faceswap#40]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/comfyui-instantId-faceswap/node.py", line 218, in create_pipeline
    pipe.load_ip_adapter_instantid(ipadapter)
  File "/root/ComfyUI/custom_nodes/comfyui-instantId-faceswap/pipeline_stable_diffusion_xl_instantid_inpaint.py", line 73, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "/root/ComfyUI/custom_nodes/comfyui-instantId-faceswap/pipeline_stable_diffusion_xl_instantid_inpaint.py", line 92, in set_image_proj_model
    state_dict = torch.load(model_ckpt, map_location="cpu")
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '@'.

**Comment by nosiu** [comment]
(hopefully) no longer relevant, since the version update
