### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by flynet** [nosiu/comfyui-instantId-faceswap#47]
Thanks for your work. What this could be ?
Python 3.11.8

got prompt
```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: G:\ComfyUI\models\insightface\models\antelopev2\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: G:\ComfyUI\models\insightface\models\antelopev2\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: G:\ComfyUI\models\insightface\models\antelopev2\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: G:\ComfyUI\models\insightface\models\antelopev2\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: G:\ComfyUI\models\insightface\models\antelopev2\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
The config attributes {'interpolation_type': 'linear', 'skip_prk_steps': True} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
!!! Exception during processing!!! zero-size array to reduction operation minimum which has no identity
Traceback (most recent call last):
  File "G:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\custom_nodes\comfyui-instantId-faceswap\node.py", line 321, in faceswap
    p_x1, p_y1, p_x2, p_y2 = getMaskBboxWithPadding(mask_image, padding)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\custom_nodes\comfyui-instantId-faceswap\node.py", line 91, in getMaskBboxWithPadding
    m_x1 = int(np.min(mask_segments[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\numpy\core\fromnumeric.py", line 2953, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python11\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation minimum which has no identity
```

Error occurred when executing FaceSwapGenerationInpaint:
```
zero-size array to reduction operation minimum which has no identity
File "G:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI\custom_nodes\comfyui-instantId-faceswap\node.py", line 321, in faceswap
p_x1, p_y1, p_x2, p_y2 = getMaskBboxWithPadding(mask_image, padding)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI\custom_nodes\comfyui-instantId-faceswap\node.py", line 91, in getMaskBboxWithPadding
m_x1 = int(np.min(mask_segments[1]))
^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python11\Lib\site-packages\numpy\core\fromnumeric.py", line 2953, in min
return _wrapreduction(a, np.minimum, 'min', axis, None, out,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Python11\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by abhinavzspace** [comment]
Getting exactly the same error.

**Comment by nosiu** [comment]
do you draw a mask and connect it to the generation node?

**Comment by nosiu** [comment]
> I'm reffering to workflow examples provided https://github.com/nosiu/comfyui-instantId-faceswap/tree/main/workflows Can you add to this flow nodes for drawing masks ? and we will test )

Right click on LoadImage Node (Original Image, or whatever it is called) and select "Open in MaskEditor"

**Comment by flynet** [comment]
Right,  I see what image mask  means  now. 
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/1836148/e4bc91eb-ac60-4b7b-88ca-c8451aeb484b)
then it throws https://github.com/nosiu/comfyui-instantId-faceswap/issues/22
Thanks
