### ISSUE TITLE
Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

### ISSUE THREAD

**Issue by wenter** [nosiu/comfyui-instantId-faceswap#5]
download_path: D:\ComfyUI_windows_portable2\ComfyUI\models\insightface\models\antelopev2
Downloading D:\ComfyUI_windows_portable2\ComfyUI\models\insightface\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\comfyui-instantId-faceswap\node.py", line 178, in create_pipeline
    app = FaceAnalysis(name="antelopev2",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\insightface\utils\download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

Prompt executed in 0.57 seconds

**Comment by nosiu** [comment]
try downloading antelopev2.zip from the link in the readme
