### ISSUE TITLE
FaceSwapSetupPipeline error

### ISSUE THREAD

**Issue by CaiNiaoCYY** [nosiu/comfyui-instantId-faceswap#50]
Loading pipeline components...:   0%|                                                                                          | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.12it/s]
!!! Exception during processing!!! /data/miniconda3/envs/env-3.10/lib/python3.10/distutils/core.py
Traceback (most recent call last):
  File "/mnt/gyfs/walteryu/Another-ComfyUI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/gyfs/walteryu/Another-ComfyUI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/gyfs/walteryu/Another-ComfyUI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/gyfs/walteryu/Another-ComfyUI/ComfyUI/custom_nodes/comfyui-instantId-faceswap/node.py", line 211, in create_pipeline
    pipe = StableDiffusionXLInstantIDInpaintPipeline.from_single_file(
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 556, in from_single_file
    pipe = pipeline_class(**init_kwargs)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py", line 243, in __init__
    self.register_modules(
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 159, in register_modules
    library, class_name = _fetch_class_library_tuple(module)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 733, in _fetch_class_library_tuple
    not_compiled_module = _unwrap_model(module)
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 236, in _unwrap_model
    from peft import PeftModel
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/mapping.py", line 22, in <module>
    from .mixed_model import PeftMixedModel
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/mixed_model.py", line 26, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/tuners/__init__.py", line 26, in <module>
    from .boft import BOFTConfig, BOFTModel
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/tuners/boft/__init__.py", line 16, in <module>
    from .layer import BOFTLayer
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/peft/tuners/boft/layer.py", line 30, in <module>
    from torch.utils.cpp_extension import load
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 9, in <module>
    import setuptools
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 70, in do_override
    ensure_local_distutils()
  File "/data/miniconda3/envs/env-3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 57, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /data/miniconda3/envs/env-3.10/lib/python3.10/distutils/core.py
#1 [FaceSwapSetupPipeline]: 81.40s

**Comment by nosiu** [comment]
(hopefully) no longer relevant, since the version update
