### ISSUE TITLE
Cannot import PipelineImageInput

### ISSUE THREAD

**Issue by lyranmahir4** [nosiu/comfyui-instantId-faceswap#8]
```
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'

Cannot import /workspace/ComfyUI/custom_nodes/.ipynb_checkpoints module for custom nodes: [Errno 2] No such file or directory: '/workspace/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-InstantID/__init__.py", line 2, in <module>
    from .nodes import InstantIDSampler
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-InstantID/nodes.py", line 7, in <module>
    from .pipeline_stable_diffusion_xl_instantid import StableDiffusionXLInstantIDPipeline, draw_kps
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-InstantID/pipeline_stable_diffusion_xl_instantid.py", line 26, in <module>
    from diffusers.image_processor import PipelineImageInput
ImportError: cannot import name 'PipelineImageInput' from 'diffusers.image_processor' (/usr/local/lib/python3.10/dist-packages/diffusers/image_processor.py)

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-InstantID module for custom nodes: cannot import name 'PipelineImageInput' from 'diffusers.image_processor' (/usr/local/lib/python3.10/dist-packages/diffusers/image_processor.py)

```

In addition, I get these on the existing workflows:
**When loading the graph, the following node types were not found:
FaceSwapSetupPipeline
FaceEmbed
FaceSwapGenerationInpaint
Nodes that have failed to load will show as red on the graph.**

**Comment by nosiu** [comment]
what's your diffusers version? requirements.txt should install 0.25.0

**Comment by lyranmahir4** [comment]
Fixed now, It was having trouble because of another existing custom node of instantID
But now I get this error:
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip


> what's your diffusers version? requirements.txt should install 0.25.0

**Comment by lyranmahir4** [comment]
I have already downloaded the models manually as the readme instructions say, still this error keeps coming back

**Comment by nosiu** [comment]
download the antelopev2 files from the link in readme

**Comment by nosiu** [comment]
There was an error in the readme. You cannot add a path for insightface inside YAML file.
It needs to be in ComfyUI/models/

**Comment by nosiu** [comment]
no longer relevant since the version update
